

package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.5
//
// Created by Quasar Development at 14-04-2014
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.HttpTransportSE;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class RIKcnsServicePortBinding
{
    interface RIKIWcfMethod
    {
        RIKExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(RIKExtendedSoapSerializationEnvelope envelope,SoapObject result) throws java.lang.Exception;
    }

    String url="http://54.186.110.123:8080/CNSServer/CNSController";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;

    public RIKcnsServicePortBinding(){}

    public RIKcnsServicePortBinding(String url)
    {
        this.url = url;
    }

    public RIKcnsServicePortBinding(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }



    java.lang.Object getResult(java.lang.Class destObj,SoapObject source,String resultName,RIKExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if (source.hasProperty(resultName))
        {
            java.lang.Object j=source.getProperty(resultName);
            if(j==null)
            {
                return null;
            }
            java.lang.Object instance=__envelope.get(j,destObj);
            return instance;
        }
        else if( source.getName().equals(resultName)) {
            java.lang.Object instance=__envelope.get(source,destObj);
            return instance;
        }
        return null;
    }
    
    public String saveWifiFingerPrints(final RIKsaveWifiFingerPrints saveWifiFingerPrints ) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=new HttpTransportSE(url,timeOut);
                RIKExtendedSoapSerializationEnvelope __envelope = new RIKExtendedSoapSerializationEnvelope();
                __envelope.addMapping("http://services.cns.com/","saveWifiFingerPrints",new RIKsaveWifiFingerPrints().getClass());
                __envelope.setOutputSoapObject(saveWifiFingerPrints);

        __httpTransport.call("", __envelope,httpHeaders);
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            SoapObject __result=(SoapObject)__retObj;
                java.lang.Object obj = __result.getProperty("return");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) __result.getProperty("return");
                    return j.toString();
                }
                return null;

        }
    }
    
    public RIKgetDirectionsResponse getDirections(final RIKpoint arg0,final RIKpoint arg1 ) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=new HttpTransportSE(url,timeOut);
                RIKExtendedSoapSerializationEnvelope __envelope = new RIKExtendedSoapSerializationEnvelope();
                __envelope.addMapping("","arg0",new RIKpoint().getClass());
                __envelope.addMapping("","arg1",new RIKpoint().getClass());
                SoapObject __soapReq = new SoapObject("http://services.cns.com/", "getDirections");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=RIKpoint.class;
                __info.setValue(arg0);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=RIKpoint.class;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);

        __httpTransport.call("", __envelope,httpHeaders);
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            SoapObject __result=(SoapObject)__retObj;
                return (RIKgetDirectionsResponse)getResult(RIKgetDirectionsResponse.class,__result,"getDirectionsResponse",__envelope);

        }
    }
    
    public RIKgetDirectionsTestResponse getDirectionsTest(final RIKpoint arg0,final RIKpoint arg1 ) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=new HttpTransportSE(url,timeOut);
                RIKExtendedSoapSerializationEnvelope __envelope = new RIKExtendedSoapSerializationEnvelope();
                __envelope.addMapping("","arg0",new RIKpoint().getClass());
                __envelope.addMapping("","arg1",new RIKpoint().getClass());
                SoapObject __soapReq = new SoapObject("http://services.cns.com/", "getDirectionsTest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=RIKpoint.class;
                __info.setValue(arg0);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=RIKpoint.class;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);

        __httpTransport.call("", __envelope,httpHeaders);
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            SoapObject __result=(SoapObject)__retObj;
                return (RIKgetDirectionsTestResponse)getResult(RIKgetDirectionsTestResponse.class,__result,"getDirectionsTestResponse",__envelope);

        }
    }
    
    public RIKgetDirectionsTest22Response getDirectionsTest22(final RIKpoint arg0,final RIKpoint arg1 ) throws java.lang.Exception
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public RIKgetUserEstimationResponse getUserEstimation(final RIKgetUserEstimation_arg0 arg0 ) throws java.lang.Exception
    {
        /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
        
   
      

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,RIKExtendedSoapSerializationEnvelope envelope)
    {
        return new java.lang.Exception(fault.faultstring);
    }
}


