package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.5
//
// Created by Quasar Development at 14-04-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RIKpointDistance extends AttributeContainer implements KvmSerializable
{
    
    public String distance;
    
    public RIKpoint point;

    public RIKpointDistance ()
    {
    }

    public RIKpointDistance (AttributeContainer inObj,RIKExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        SoapObject soapObject=(SoapObject)inObj;  

        if (soapObject.hasProperty("distance"))
        {	
	        java.lang.Object obj = soapObject.getProperty("distance");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.distance = j.toString();
                }
	        }
	        else if (obj!= null){
                this.distance = obj.toString();
            }    
        }
        if (soapObject.hasProperty("point"))
        {	
	        java.lang.Object j = soapObject.getProperty("point");
	        this.point = (RIKpoint)envelope.get(j,RIKpoint.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        if(propertyIndex==0)
        {
            return distance;
        }
        if(propertyIndex==1)
        {
            return point;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "distance";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = RIKpoint.class;
            info.name = "point";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
