package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.5
//
// Created by Quasar Development at 14-04-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class RIKwifiAccessPoint extends AttributeContainer implements KvmSerializable
{
    
    public String bssid;
    
    public String dbm;
    
    public String ssid;
    
    public String strength;

    public RIKwifiAccessPoint ()
    {
    }

    public RIKwifiAccessPoint (AttributeContainer inObj,RIKExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        SoapObject soapObject=(SoapObject)inObj;  

        if (soapObject.hasProperty("bssid"))
        {	
	        java.lang.Object obj = soapObject.getProperty("bssid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.bssid = j.toString();
                }
	        }
	        else if (obj!= null){
                this.bssid = obj.toString();
            }    
        }
        if (soapObject.hasProperty("dbm"))
        {	
	        java.lang.Object obj = soapObject.getProperty("dbm");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.dbm = j.toString();
                }
	        }
	        else if (obj!= null){
                this.dbm = obj.toString();
            }    
        }
        if (soapObject.hasProperty("ssid"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ssid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ssid = j.toString();
                }
	        }
	        else if (obj!= null){
                this.ssid = obj.toString();
            }    
        }
        if (soapObject.hasProperty("strength"))
        {	
	        java.lang.Object obj = soapObject.getProperty("strength");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.strength = j.toString();
                }
	        }
	        else if (obj!= null){
                this.strength = obj.toString();
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        if(propertyIndex==0)
        {
            return bssid;
        }
        if(propertyIndex==1)
        {
            return dbm;
        }
        if(propertyIndex==2)
        {
            return ssid;
        }
        if(propertyIndex==3)
        {
            return strength;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "bssid";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "dbm";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ssid";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "strength";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
