package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.8
//
// Created by Quasar Development at 23-04-2014
//
//---------------------------------------------------



public interface BSKIServiceEvents
{
    public void Starting();
    public void Completed(BSKOperationResult result);
}
