package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.8
//
// Created by Quasar Development at 23-04-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BSKpoint extends AttributeContainer implements KvmSerializable
{
    
    public BSKpoint_accessPoints accessPoints=new BSKpoint_accessPoints();
    
    public String partition;
    
    public String x;
    
    public String y;
    
    public String z;

    public BSKpoint ()
    {
    }

    public BSKpoint (AttributeContainer inObj,BSKExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        SoapObject soapObject=(SoapObject)inObj;  

        if (soapObject.hasProperty("accessPoints"))
        {	
	        java.lang.Object j = soapObject.getProperty("accessPoints");
	        this.accessPoints = new BSKpoint_accessPoints((AttributeContainer)j,envelope);
        }
        if (soapObject.hasProperty("partition"))
        {	
	        java.lang.Object obj = soapObject.getProperty("partition");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.partition = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.partition = (String)obj;
            }    
        }
        if (soapObject.hasProperty("x"))
        {	
	        java.lang.Object obj = soapObject.getProperty("x");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.x = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.x = (String)obj;
            }    
        }
        if (soapObject.hasProperty("y"))
        {	
	        java.lang.Object obj = soapObject.getProperty("y");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.y = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.y = (String)obj;
            }    
        }
        if (soapObject.hasProperty("z"))
        {	
	        java.lang.Object obj = soapObject.getProperty("z");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.z = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.z = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        if(propertyIndex==0)
        {
            return accessPoints;
        }
        if(propertyIndex==1)
        {
            return partition;
        }
        if(propertyIndex==2)
        {
            return x;
        }
        if(propertyIndex==3)
        {
            return y;
        }
        if(propertyIndex==4)
        {
            return z;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "accessPoints";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "partition";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "x";
            info.namespace= "";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "y";
            info.namespace= "";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "z";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
