package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.8
//
// Created by Quasar Development at 23-04-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BSKpoint_accessPoints_entry extends AttributeContainer implements KvmSerializable
{
    
    public String key;
    
    public String value;

    public BSKpoint_accessPoints_entry ()
    {
    }

    public BSKpoint_accessPoints_entry (AttributeContainer inObj,BSKExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        SoapObject soapObject=(SoapObject)inObj;  

        if (soapObject.hasProperty("key"))
        {	
	        java.lang.Object obj = soapObject.getProperty("key");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.key = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.key = (String)obj;
            }    
        }
        if (soapObject.hasProperty("value"))
        {	
	        java.lang.Object obj = soapObject.getProperty("value");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.value = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.value = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        if(propertyIndex==0)
        {
            return key;
        }
        if(propertyIndex==1)
        {
            return value;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "key";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "value";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
